# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformDexter < Formula
  desc "Gini-internal version of dexter"
  homepage "https://github.com/gini/platform-dexter/"
  version "0.5.1+gini"

  on_macos do
    url "https://repo.i.gini.net/nexus/repository/homebrew-tap/platform/dexter/0.5.1+gini/dexter_0.5.1+gini_Darwin_all.tar.gz"
    sha256 "d9fa1fee54cce2cd5c15a8d6d4cfd0676477ba58ce5dac3ef033b281cc5f4685"

    def install
      bin.install "dexter"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://repo.i.gini.net/nexus/repository/homebrew-tap/platform/dexter/0.5.1+gini/dexter_0.5.1+gini_Linux_x86_64.tar.gz"
      sha256 "a0327431531ee4db1ffaba796f7aec28394b4394fc7eabd1a9d63362cb9b63ee"

      def install
        bin.install "dexter"
      end
    end
  end

  depends_on "kubernetes-cli"
end
