# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformDexter < Formula
  desc "Gini-internal version of dexter"
  homepage "https://github.com/gini/platform-dexter/"
  version "0.5.2+gini"

  on_macos do
    url "https://repo.i.gini.net/nexus/repository/homebrew-tap/platform/dexter/0.5.2+gini/dexter_0.5.2+gini_Darwin_all.tar.gz"
    sha256 "b1c6bafa83c3d7b29ad55bc2131cca101b4da96ad3aadcd068a85b866e0425cd"

    def install
      bin.install "dexter"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://repo.i.gini.net/nexus/repository/homebrew-tap/platform/dexter/0.5.2+gini/dexter_0.5.2+gini_Linux_x86_64.tar.gz"
      sha256 "46ca4828e8888e03d7b3b364d610fd12d3c9efa83b5c1359934dcef38fb2cfe0"

      def install
        bin.install "dexter"
      end
    end
  end

  depends_on "kubernetes-cli"
end
